# Use the official node image as a parent image
FROM node:18

# Set the working directory
WORKDIR /app

# COPY ./chain/out ./chain/out
COPY . .
curl -L https://foundry.paradigm.xyz | bash

# Install dependencies and setup
RUN yarn install
RUN git submodule update --init --recursive
yarn setup

EXPOSE 8080
# Specify the command to run on container start
CMD ["yarn", "dev"]
